version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 252211984
      POSTGRES_DB: testdb
    networks:
      - nestjs-network

networks:
  nestjs-network:

#docker compose up -d

